INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('tandem','Angers',45);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('tandem','Angers',45);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('tandem','Angers',45);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('tandem','Paris',45);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('tandem','Paris',45);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Angers',20);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Angers',20);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Angers',20);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Angers',25);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Angers',25);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Angers',25);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Paris',25);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Paris',25);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Paris',25);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Paris',25);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Paris',25);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Paris',30);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Paris',30);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Paris',30);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo de ville','Paris',30);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo electrique','Angers',40);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo electrique','Angers',40);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo electrique','Angers',40);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo electrique','Paris',45);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo electrique','Paris',45);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo electrique','Paris',45);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo electrique','Paris',45);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo electrique','Paris',45);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo electrique','Paris',50);
INSERT INTO Velos (categorie, ville, prixLocationDeBase) VALUES ('velo electrique','Paris',55);

INSERT INTO Clients (login,password,nom,prenom,mail,telephone,adresse) VALUES('monsieur','patate','Sarah','Croche','sarah.croche@gmail.com','0654896523','19 rue des bisounours');
INSERT INTO Clients (login,password,nom,prenom,mail,telephone,adresse) VALUES('pitou35','pelerin35','Pierre-Antoine','Pelerin','pierreantoine.pelerin@gmail.com','0699079223','19 rue Pierre Lise');
INSERT INTO Reservations (idClient,idVelo,dateLocationDebut,dateLocationFin,paimentEffectue) VALUES (1,20,'2017-04-12','2017-04-14',false);
INSERT INTO Reservations (idClient,idVelo,dateLocationDebut,dateLocationFin,paimentEffectue) VALUES (1,14,'2017-04-16','2017-04-18',false);
INSERT INTO Reservations (idClient,idVelo,dateLocationDebut,dateLocationFin,paimentEffectue) VALUES (2,5,'2017-04-12','2017-04-14',false);
INSERT INTO Reservations (idClient,idVelo,dateLocationDebut,dateLocationFin,paimentEffectue) VALUES (2,7,'2017-04-12','2017-04-14',false);
DELETE FROM Reservations WHERE idReservation = 4;
INSERT INTO Annulations (idReservation,idClient,idVelo,dateLocationDebut,dateLocationFin,paimentEffectue) VALUES (4,2,7,'2017-04-12','2017-04-14',false);